version: '3.8'
services:
  backend:
    container_name: admin_backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: [ sh, -c, 'sleep 10 &&  python manage.py migrate &&  python manage.py runserver 0.0.0.0:8000'] # first time run
    # command: [ sh, -c, 'sleep 10 &&  python manage.py runserver 0.0.0.0:8000'] # regular run 
    # command: [ sh, -c, 'sleep infinity'] # regular run 
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - ./mysqld:/var/run/mysqld:rw
    depends_on:
      - db

  queue:
    container_name: admin_queue
    build:
      context: .
      dockerfile: Dockerfile
    command: [sh, -c , 'sleep 10 && python -u consumer.py']
    # command: [ sh, -c, 'sleep infinity'] # regular run 
    env_file:
      - .env
    volumes:
      - .:/app
      - ./mysqld:/var/run/mysqld:rw
    depends_on:
      - db

  db:
    container_name: admin_db
    image: arm64v8/mysql:oracle # for M1 mac
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    user: mysql
    volumes:
      - .dbdata:/var/lib/mysql:rw
      - ./mysqld:/var/run/mysqld:rw
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33066:3306
